### ISSUE TITLE
Crashes on any locale other than English and Arabic

### ISSUE THREAD

**Issue by guidedways** [msarhan/ummalqura-calendar#11]
This line:

`ResourceBundle resource = ResourceBundle.getBundle("com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData", locale);`

crashes the app if run on French / German / Russian etc as the bundle only includes _ar and _en. This should be done in a try / catch and if a locale isn't found, English should be used.

**Comment by msarhan** [comment]
Added check for supported locale.
I think it is not good to fallback to English locale if the provided locale is not supported.
Thanks!

**Comment by AmineMessabhia** [comment]
@guidedways , i know this is way too late

but for anyone else coming here, you can always download the library, and use it in ur project, and simply add classes for any other language, then manually translate the months' names to that language, and don't forget to add the condition for your language, otherwise it'd keep throwing the Exception.

**Comment by msarhan** [comment]
@guidedways I was wrong about refusing fallback solution if the current locale is not supported as this library could be used on mobile devices with no control of the used locale.

Thanks to @AmineMessabhia for the suggestion. 
I've added the possibility to add new locale using properties files which is much easier than creating Java class for localization. And in case of missing locale, it will fallback to ENGLISH locale.

Please check [v1.2.0](https://github.com/msarhan/ummalqura-calendar/tree/1.2.0)
